# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coo_desc <- function(X, M, w, gamma, s = 10L, lambda = 0.15, k = 5L, max_iter = 100L, update_phi_every = 1L, w_sparse = 0L) {
    .Call(`_l0fcl_coo_desc`, X, M, w, gamma, s, lambda, k, max_iter, update_phi_every, w_sparse)
}

soft <- function(x, T) {
    .Call(`_l0fcl_soft`, x, T)
}

proj_simplex_l0 <- function(x, s, D) {
    .Call(`_l0fcl_proj_simplex_l0`, x, s, D)
}

proj_simplex_l1 <- function(x, lambda, D) {
    .Call(`_l0fcl_proj_simplex_l1`, x, lambda, D)
}

rcpparma_hello_world <- function() {
    .Call(`_l0fcl_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_l0fcl_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_l0fcl_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_l0fcl_rcpparma_bothproducts`, x)
}

